const DARK_MAP_COLORS = {
    bg: '#0A0A0A',
    boundary: '#666',
    roadCase: "#666",
    roadFill: '#000',
    roadLinePri: '#222',
    roadCasePri: '#555',
    roadFillPri: '#222',
    roadLineMot: '#222',
    roadCaseMot: '#444',
    roadFillMot: '#3F3F3F',
    roadLineTrunk: '#222',
    roadCaseTrunk: '#444',
    roadFillTrunk: '#3F3F3F',
    waterBg: 'rgb(21, 30, 36)',
    waterStroke: '#000',
    waterLabelColor: '#bbb',
    landcoverBg: '#0A0A0A',
    landcoverStroke: '#fff',
    buildingBg: '#111',
    buildingStroke: '#666',
} as const;

const LIGHT_MAP_COLORS = {
    bg: '#fff',
    boundary: '#999',
    roadCase: "#888",
    roadFill: '#ddd',
    roadLinePri: '#ddd',
    roadLineTrunk: '#ddd',
    roadLineMot: '#ddd',
    roadCasePri: '#eee',
    roadCaseTrunk: '#eee',
    roadCaseMot: '#eee',
    roadFillPri: '#ddd',
    roadFillTrunk: '#ddd',
    roadFillMot: '#ddd',
    waterBg: '#ddd', // fix water color in light mode to blue 
    waterStroke: '#fff',
    waterLabelColor: '#444',
    landcoverBg: '#fff',
    landcoverStroke: '#000',
    buildingBg: '#eee',
    buildingStroke: '#aaa',
} as const;

export const MAP_COLORS = {
    light: LIGHT_MAP_COLORS,
    dark: DARK_MAP_COLORS,
} as const;